swagger: '2.0'
info:
  version: 0.1.0
  description: >-
    A tiles service
  title: tiles geoapi
  # put the contact info for your development or API team
  contact:
    email: contact@geoapi.fr

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

schemes:
  - http
paths:
  /:
    get:
      tags: [metadata]
      summary: Returns the list of exposed datasets and some query examples
      operationId: serviceCapabilities
      produces:
        - text/html
        - application/json
      responses:
        '200':
          description: opération réussie
          schema:
            $ref: '#/definitions/servicemetadata'
  '/{dsid}':
    get:
      tags: [metadata]
      summary: the dataset URI returns the dataset metadata
      description: >-
        the dataset URI returns the dataset metadata
      operationId: datasetUri
      produces:
        - application/json
      parameters:
        - name: dsid
          in: path
          description: ID of the dataset
          required: true
          type: string
      responses:
        '200':
          description: the dataset metadata
          schema:
            $ref: '#/definitions/datasetmetadata'
        '404':
          description: no dataset corresponds to this URI
  '/{dsid}/layers':
    get:
      tags: [metadata]
      summary: list of layers
      operationId: datasetLayers
      produces:
        - application/json
      parameters:
        - name: dsid
          in: path
          description: ID of the dataset
          required: true
          type: string
      responses:
        '200':
          description: the list of layers of the dataset
          schema:
            $ref: '#/definitions/listOfLayers'
        '404':
          description: no dataset corresponds to this URI
  '/{dsid}/layers/{lyrid}':
    get:
      tags: [metadata]
      summary: layer's metadata
      operationId: layermetadata
      produces:
        - application/json
      parameters:
        - name: dsid
          in: path
          description: ID of the dataset
          required: true
          type: string
        - name: lyrid
          in: path
          description: ID of the layer
          required: true
          type: string
      responses:
        '200':
          description: the list of layers of the dataset
          schema:
            $ref: '#/definitions/layermetadata'
        '404':
          description: no dataset corresponds to this URI
  '/{dsid}/layers/{lyrid}/{zoom}/{x}/{y}.{fmt}':
    get:
      tags: [image]
      summary: returns a tile or an Html page showing it
      operationId: tile
      produces:
        - image/jpeg
        - image/png
        - text/html
      parameters:
        - name: dsid
          in: path
          description: ID of the dataset
          required: true
          type: string
        - name: lyrid
          in: path
          description: ID of the layer
          required: true
          type: string
        - name: zoom
          in: path
          description: zoom of the tile
          required: true
          type: integer
        - name: x
          in: path
          description: x of the tile
          required: true
          type: integer
        - name: y
          in: path
          description: y of the tile
          required: true
          type: integer
        - name: fmt
          in: path
          description: format of the tile or html
          required: true
          type: string
          enum: [jpg, png, html]
      responses:
        '200':
          description: the tile or an Html page showing it
        '404':
          description: no tile corresponds to this URL

definitions:
  servicemetadata:
    type: object
    description: >-
      service metadata
    properties:
      title:
        type: string
      abstract:
        type: string
      self:
        type: string
      version:
        type: string
      api:
        type: object
        properties:
          title:
            type: string
          href:
            type: string
      datasets:
        type: object
        additionalProperties:
          type: object
          properties:
            title:
              type: string
            href:
              type: string
      examples:
        type: array
        items:
          type: object
          properties:
            title:
              type: string
              description: description of the example
            href:
              type: string
              description: URL of the example
  datasetmetadata:
    type: object
    description: >-
      dataset metadata
    properties:
      title:
        type: string
      abstract:
        type: string
      licence:
        type: object
        properties:
          identifier:
            type: string
          title:
            type: string
      spatial:
        type: object
        properties:
          name:
            type: string
          westlimit:
            type: number
          southlimit:
            type: number
          eastlimit:
            type: number
          northlimit:
            type: number
      self:
        type: string
      layers:
        type: object
        properties:
          title:
            type: string
          href:
            type: string
  listOfLayers:
    type: object
    description: >-
      list of layers
    additionalProperties:
      type: object
      properties:
        title:
          type: string
        href:
          type: string
  layermetadata:
    type: object
    description: >-
      list of layers
    properties:
      title:
        type: string
      self:
        type: string
      abstract:
        type: string
      format:
        type: string
        enum: [image/jpeg, image/png]
      minzoom:
        type: integer
      maxzoom:
        type: integer
host: tiles.geoapi.fr
basePath: /
# schemes:
#  - http
# Added by API Auto Mocking Plugin
#host: virtserver.swaggerhub.com
#basePath: /benoitdavidfr/tiles/1.0.0

externalDocs:
  description: Documentation of the API
  url: https://github.com/benoitdavidfr/geoinfra